# Generated by Django 5.2.4 on 2025-08-16 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('major_code', models.CharField(blank=True, max_length=50, null=True)),
                ('degree_type', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('college_name', models.CharField(blank=True, max_length=100, null=True)),
                ('main_subject', models.TextField(blank=True, null=True)),
                ('related_career', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=50)),
                ('school_code', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('school_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('experience', models.TextField(blank=True, null=True)),
                ('conversation_style', models.CharField(blank=True, choices=[('casual', '수다형'), ('deep', '깊은대화형'), ('humor', '유머형'), ('debate', '토론형')], max_length=100, null=True)),
                ('activity_location', models.CharField(blank=True, max_length=100, null=True)),
                ('goal_or_concern', models.TextField(blank=True, null=True)),
                ('personality_keyword', models.ManyToManyField(blank=True, to='profiles.personality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '남자'), ('F', '여자')], max_length=1, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('mbti', models.CharField(blank=True, choices=[('INTJ', 'INTJ'), ('INTP', 'INTP'), ('ENTJ', 'ENTJ'), ('ENTP', 'ENTP'), ('INFJ', 'INFJ'), ('INFP', 'INFP'), ('ENFJ', 'ENFJ'), ('ENFP', 'ENFP'), ('ISTJ', 'ISTJ'), ('ISFJ', 'ISFJ'), ('ESTJ', 'ESTJ'), ('ESFJ', 'ESFJ'), ('ISTP', 'ISTP'), ('ISFP', 'ISFP'), ('ESTP', 'ESTP'), ('ESFP', 'ESFP')], max_length=4, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('current_step', models.CharField(choices=[('step1', '1단계 - 학교정보'), ('step2', '2단계 - 관심사'), ('step3', '3단계 - 공강시간'), ('step4', '4단계 - 기본정보'), ('step5', '5단계 - 추가정보'), ('completed', '완료')], default='step1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profiles.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
