# Generated by Django 5.2.4 on 2025-08-04 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interests', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profileinterest',
            name='interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.interest'),
        ),
        migrations.AddField(
            model_name='profileinterest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profiles.school'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='profiles.school'),
        ),
        migrations.AlterUniqueTogether(
            name='profileinterest',
            unique_together={('profile', 'interest')},
        ),
    ]
