# Generated by Django 5.2.4 on 2025-08-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_completed',
        ),
    ]
