# Generated by Django 5.2.4 on 2025-08-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_personality_alter_profile_user_additionalinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_step',
            field=models.CharField(choices=[('step1', '1단계 - 학교정보'), ('step2', '2단계 - 관심사'), ('step3', '3단계 - 공강시간'), ('step4', '4단계 - 기본정보'), ('step5', '5단계 - 추가정보'), ('completed', '완료')], default='step1', max_length=20),
        ),
    ]
