# Generated by Django 5.2.5 on 2025-08-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
