# Generated by Django 5.2.4 on 2025-08-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
