# Generated by Django 5.2.4 on 2025-08-04 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
