# Generated by Django 5.2.4 on 2025-08-16 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewattitude',
            name='attitude',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.conversationattitude'),
        ),
        migrations.AddField(
            model_name='reviewattitude',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attitudes', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='reviewvalue',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='reviewvalue',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.conversationvalue'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewattitude',
            unique_together={('review', 'attitude')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewvalue',
            unique_together={('review', 'value')},
        ),
    ]
