# Generated by Django 5.2.5 on 2025-08-14 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='attitude',
        ),
        migrations.RemoveField(
            model_name='review',
            name='degree',
        ),
        migrations.AlterField(
            model_name='conversationattitude',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversationvalue',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ReviewAttitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attitude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.conversationattitude')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attitudes', to='reviews.review')),
            ],
            options={
                'unique_together': {('review', 'attitude')},
            },
        ),
        migrations.CreateModel(
            name='ReviewValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reviews.review')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.conversationvalue')),
            ],
            options={
                'unique_together': {('review', 'value')},
            },
        ),
    ]
