# Generated by Django 5.2.4 on 2025-08-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetime',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', '월'), ('Tuesday', '화'), ('Wednesday', '수'), ('Thursday', '목'), ('Friday', '금'), ('Saturday', '토'), ('Sunday', '일')], max_length=10),
        ),
    ]
