# Generated by Django 5.2.4 on 2025-08-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('대기중', '대기중'), ('수락됨', '수락됨'), ('거절됨', '거절됨')], default='대기중', max_length=10)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('request_message', models.TextField(blank=True, null=True)),
                ('refusal_message', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
