# Generated by Django 5.2.4 on 2025-08-05 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matching',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='matching',
            constraint=models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_sender_receiver'),
        ),
    ]
