# Generated by Django 5.2.5 on 2025-08-14 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatroom_completed_at_chatroom_is_completed'),
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matching',
            name='chatroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching', to='chats.chatroom'),
        ),
    ]
